import { TailwindIndicator } from "@/components/tailwind-indicator";
import { fontSans } from "@/config/fonts";
import { cn } from "@/lib/cn";
import { ThemeProvider } from "@/providers/themeProvider";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={cn(fontSans.variable)}>
      <body className="min-h-screen bg-background font-sans antialiased">
        <ThemeProvider attribute="class" defaultTheme="light">
          {children}
          <TailwindIndicator />
        </ThemeProvider>
      </body>
    </html>
  );
}
